baseURL: "https://mvallee1998.github.io" 
title: Mathieu Vallée - Mathematics webpage 
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 30

taxonomies:
    tag: tags

menu:
    main:
        - name: Research overview
          url: research/
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Photography
          url: photography/
          weight: 3
        - name: Courses
          url: courses/
          weight: 2

params:
    description: "This website hosts Mathieu Vallée's research papers, course materials, data, curriculum vitae, and contact information."
    author: Mathieu Vallée
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["Research Overview","Papers", "Courses", "Photography"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr Mathieu Vallée
          subtitle: "*Toric topology, combinatorial optimization, operad theory*<br><br>I am currently a postdoctoral researcher at Université libre de Bruxelles (ULB), supervised by [Jean Cardinal](https://jean.cardinal.web.ulb.be/). I was a doctoral student of Professor [Roland Grappe](https://www.lamsade.dauphine.fr/~rgrappe/index.html) and Professor [Bruno Vallette](https://www.math.univ-paris13.fr/~vallette/) in Paris, at [Université Sorbonne Paris Nord](https://www.univ-spn.fr/)."
          imageUrl: "Mathieu.jpg"
          imageWidth: 200
          imageHeight: 200
          buttons:
            - name: Research Overview
              url: research/
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Photography
              url: photography/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:mathieu.vallee@protonmail.com
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=user
        - name: GitHub
          url: https://github.com/mvallee1998
        - name: Arxiv
          url: https://arxiv.org/a/vallee_m_1.html
        - name: Orcid
          url: https://orcid.org/0000-0001-6336-9225


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Mathieu Vallée"
      icon: favicon.ico
      iconHeight: 28

caches:
    images:
        dir: ':cacheDir/:project'
        maxAge: -1

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2